POST http://localhost:5000/employees/profile/660c2ffc-f56b-481f-9f5e-48ed278f2444
Content-Type: application/json

{
  "birth_place": "Karawangs",
  "birth_date": "1945-08-17",
  "home_address": "Rengas Dengklok",
  "contact": "0987123456",
  "dept": "IT",
  "title": "Staff",
  "join_date": "2016-10-10",
  "nik_ktp": "1329847265934544",
  "religion": "Islam"
}