PATCH http://localhost:5000/employees/credentials/10cc9d8f-480e-455a-b7b2-f060cf978036
Content-Type: application/json

{
  "username": "yudi",
  "email": "khalidsystem18@gmail.com",
  "password": "rahasiadong",
  "confirmPassword": "rahasiadong"
}